language: python
python:
  - "3.6"
install:
  - pip3 install -r requirements.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/manage.py"
  - export FLASK_DEBUG=1
script: python3 manage.py migrate